name: language-parser
version: 0.1.0.0
github: "githubuser/language-parser"
license: BSD3
author: "Mikita Kukavenka"
maintainer: "godinfrog@gmail.com"
copyright: "2019 Mikita Kukavenka"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/language-parser#readme>

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude

dependencies:
  - base
  - classy-prelude

library:
  dependencies:
    - aeson
    - boxes
    - bytestring
    - directory
    - esqueleto
    - monad-logger
    - persistent
    - persistent-postgresql
    - persistent-template
    - postgresql-simple
    - prettyprinter
    - prettyprinter-ansi-terminal
    - regex-compat-tdfa
    - resource-pool
    - resourcet
    - scotty
    - servant
    - servant-client
    - servant-server
    - servant-swagger
    - swagger2
    - template-haskell
    - text
    - time
    - transformers
    - wai-cors
    - warp
  ghc-options:
    - "-Wall"
    - "-Werror"
    - "-Wincomplete-record-updates"
    - "-Wincomplete-uni-patterns"
    - "-Wredundant-constraints"
    - "-Wno-unused-top-binds"
    - "-O2"
  source-dirs: src

executables:
  language-parser-exe:
    dependencies:
      - language-parser
    ghc-options:
      - "-threaded"
      - "-rtsopts"
      - "-with-rtsopts=-N"
    main: Main.hs
    source-dirs: app

tests:
  language-parser-test:
    dependencies:
      - hspec
      - hspec-wai
      - hspec-wai-json
      - language-parser
      - tasty
      - tasty-hspec
    ghc-options:
      - "-threaded"
      - "-rtsopts"
      - "-with-rtsopts=-N"
    main: Spec.hs
    source-dirs: test

benchmarks:
  language-parser-benchmarks:
    dependencies:
      - criterion
      - language-parser
    ghc-options:
      - "-O2"
      - "-rtsopts"
      - "-threaded"
      - "-with-rtsopts=-N"
    main: Bench.hs
    source-dirs: bench
