name:                language-parser
version:             0.1.0.0
github:              "githubuser/language-parser"
license:             BSD3
author:              "Mikita Kukavenka"
maintainer:          "godinfrog@gmail.com"
copyright:           "2019 Mikita Kukavenka"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/language-parser#readme>

default-extensions:
- OverloadedStrings
# - GeneralizedNewtypeDeriving
- NoImplicitPrelude


dependencies:
  - base
  - classy-prelude


library:
  source-dirs: src
  dependencies:
  # - regex-compat
  - aeson
  - boxes
  - bytestring
  - directory
  - esqueleto
  - monad-logger
  - persistent
  - persistent-postgresql
  - persistent-template
  - postgresql-simple
  - prettyprinter
  - prettyprinter-ansi-terminal
  - regex-compat-tdfa
  - resource-pool
  - resourcet
  - scotty
  - servant
  - servant-client
  - servant-server
  - template-haskell
  - text
  - time
  - transformers
  - warp
  ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unused-top-binds
  - -O2

executables:
  language-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-parser
    
  
tests:
  language-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-parser
    - tasty
    - tasty-hspec
