CREATE ROLE wiki LOGIN
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

ALTER ROLE wiki PASSWORD 'wiki';

CREATE DATABASE wiki
  WITH OWNER = wiki
       TEMPLATE = template0
       ENCODING = 'UTF8'
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

ALTER DATABASE wiki OWNER TO wiki;

