version: "3.3"
networks:
  wiki-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.7.0/24

services:
  wiki-postgres:
    container_name: "wiki-postgres"
    image: wiki/postgres
    build: .
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    networks:
      wiki-network:
        ipv4_address: 172.19.7.103
        aliases:
          - postgres.wiki.lo
  wiki-flyway:
    container_name: "wiki-flyway"
    image: flyway/flyway:7.2.0
    command: -url=jdbc:postgresql://postgres.wiki.lo:5432/wiki -user=wiki -password=wiki -connectRetries=60 -ignoreMissingMigrations=true migrate
    volumes:
      - ./sql/flyway-migration:/flyway/sql/flyway-migration
      - ../test/sql/flyway-migration:/flyway/sql/flyway-migration-test
    networks:
      - wiki-network
    depends_on:
      - wiki-postgres
volumes:
  pgdata:
